// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_reason.proto

package com.gomicroim.lib.protos.user;

public final class ErrorReasonProto {
  private ErrorReasonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code user.v1.ErrorReason}
   */
  public enum ErrorReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_UNSPECIFIED = 0;</code>
     */
    USER_UNSPECIFIED(0),
    /**
     * <code>USER_NOT_FOUND = 1;</code>
     */
    USER_NOT_FOUND(1),
    /**
     * <code>TOKEN_MISS = 100;</code>
     */
    TOKEN_MISS(100),
    /**
     * <code>TOKEN_INVALID = 101;</code>
     */
    TOKEN_INVALID(101),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>USER_UNSPECIFIED = 0;</code>
     */
    public static final int USER_UNSPECIFIED_VALUE = 0;
    /**
     * <code>USER_NOT_FOUND = 1;</code>
     */
    public static final int USER_NOT_FOUND_VALUE = 1;
    /**
     * <code>TOKEN_MISS = 100;</code>
     */
    public static final int TOKEN_MISS_VALUE = 100;
    /**
     * <code>TOKEN_INVALID = 101;</code>
     */
    public static final int TOKEN_INVALID_VALUE = 101;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ErrorReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorReason forNumber(int value) {
      switch (value) {
        case 0: return USER_UNSPECIFIED;
        case 1: return USER_NOT_FOUND;
        case 100: return TOKEN_MISS;
        case 101: return TOKEN_INVALID;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorReason>() {
            public ErrorReason findValueByNumber(int number) {
              return ErrorReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ErrorReasonProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorReason[] VALUES = values();

    public static ErrorReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:user.v1.ErrorReason)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022error_reason.proto\022\007user.v1*Z\n\013ErrorRe" +
      "ason\022\024\n\020USER_UNSPECIFIED\020\000\022\022\n\016USER_NOT_F" +
      "OUND\020\001\022\016\n\nTOKEN_MISS\020d\022\021\n\rTOKEN_INVALID\020" +
      "eBI\n\035com.gomicroim.lib.protos.userB\020Erro" +
      "rReasonProtoZ\026apiuser/api/user/v1;v1b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
