// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error_reason.proto

package com.gomicroim.lib.protos.chat;

public final class ErrorReasonProto {
  private ErrorReasonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * chat 错误代码定义
   * </pre>
   *
   * Protobuf enum {@code apichat.ErrorReason}
   */
  public enum ErrorReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GEETER_UNSPECIFIED = 0;</code>
     */
    GEETER_UNSPECIFIED(0),
    /**
     * <code>USER_NOT_FOUND = 1;</code>
     */
    USER_NOT_FOUND(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GEETER_UNSPECIFIED = 0;</code>
     */
    public static final int GEETER_UNSPECIFIED_VALUE = 0;
    /**
     * <code>USER_NOT_FOUND = 1;</code>
     */
    public static final int USER_NOT_FOUND_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ErrorReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorReason forNumber(int value) {
      switch (value) {
        case 0: return GEETER_UNSPECIFIED;
        case 1: return USER_NOT_FOUND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorReason>() {
            public ErrorReason findValueByNumber(int number) {
              return ErrorReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ErrorReasonProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorReason[] VALUES = values();

    public static ErrorReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:apichat.ErrorReason)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022error_reason.proto\022\007apichat*9\n\013ErrorRe" +
      "ason\022\026\n\022GEETER_UNSPECIFIED\020\000\022\022\n\016USER_NOT" +
      "_FOUND\020\001BI\n\035com.gomicroim.lib.protos.cha" +
      "tB\020ErrorReasonProtoZ\026apichat/api/chat/v1" +
      ";v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
